"""change comprehension_level to string type

Revision ID: 171dfa425590
Revises: b3c4d5e6f7g8
Create Date: 2025-11-09 16:15:08.861444

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '171dfa425590'
down_revision: Union[str, None] = 'b3c4d5e6f7g8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Change comprehension_level from Enum to String to avoid uppercase conversion issues
    op.alter_column('chat_session', 'comprehension_level',
               existing_type=sa.Enum('low', 'medium', 'high', name='comprehensionlevel'),
               type_=sa.String(50),
               existing_nullable=True)

    op.drop_column('chat_config', 'analysis_prompt')
    op.alter_column('model', 'order',
               existing_type=sa.INTEGER(),
               nullable=True,
               existing_server_default=sa.text('0'))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Revert comprehension_level back to Enum
    op.alter_column('chat_session', 'comprehension_level',
               existing_type=sa.String(50),
               type_=sa.Enum('low', 'medium', 'high', name='comprehensionlevel'),
               existing_nullable=True)

    op.alter_column('model', 'order',
               existing_type=sa.INTEGER(),
               nullable=False,
               existing_server_default=sa.text('0'))
    op.add_column('chat_config', sa.Column('analysis_prompt', sa.TEXT(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
