"""add_order_column_to_model

Revision ID: c82c550cf83d
Revises: f1a2b3c4d5e6
Create Date: 2025-10-28 10:35:19.841408

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c82c550cf83d'
down_revision: Union[str, None] = 'f1a2b3c4d5e6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('model', sa.Column('order', sa.Integer(), nullable=False, server_default='0'))
    op.create_index(op.f('ix_model_order'), 'model', ['order'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_model_order'), table_name='model')
    op.drop_column('model', 'order')
    # ### end Alembic commands ###
