"""remove config and is_active from model table

Revision ID: e7b67a707145
Revises: 683738efbac7
Create Date: 2025-10-24 22:49:49.411632

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'e7b67a707145'
down_revision: Union[str, None] = '683738efbac7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_model_is_active', table_name='model')
    op.drop_column('model', 'is_active')
    op.drop_column('model', 'config')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('model', sa.Column('config', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True))
    op.add_column('model', sa.Column('is_active', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.create_index('ix_model_is_active', 'model', ['is_active'], unique=False)
    # ### end Alembic commands ###
